_target_: pytorch_lightning.Trainer

default_root_dir: ${paths.output_dir}

accelerator: gpu
devices: 1

min_epochs: 1
max_epochs: 10

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# mixed precision for extra speed-up
# precision: 16

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

# overfit batch
overfit_batches: 100

# ckpt path
resume_from_checkpoint: null
